telemetry:
  level: "info,ai_gateway=trace"
  exporter: both

server:
  port: 8080

helicone:
  base-url: "http://localhost:8585"
  websocket-url: "ws://localhost:8585/ws/v1/router/control-plane"
  features: all

routers:
  latency:
    load-balance:
      chat:
        strategy: model-latency
        models:
          - openai/gpt-4o-mini
          - anthropic/claude-3-7-sonnet
  my-router:
    load-balance:
      chat:
        strategy: model-latency
        models:
          - bedrock/anthropic.claude-3-7-sonnet-v1:0
          - anthropic/claude-3-7-sonnet